### ISSUE TITLE
Vision/Roadmap

### ISSUE THREAD

**Issue by mjackson** [reactjs/react-router#3289]
We need to be more effective at communicating our vision for the router. Hopefully we can do this constructively out in the open and get everyone's feedback. Also, I hope this document gives some guidance to people who've asked how they can help.

For now, here's a list of stuff that needs to happen, in no particular order:

- [x] Support trailing slashes. This was originally merged in #3158, reverted by @timdorr in #3280 (not sure why) and merged again in #3285. Needs a release.
- [x] Simplify `<Link>` active semantics (depends on #3158, see #3231 for discussion)
- [ ] Remove nested absolute paths (see #3172 for discussion, #3246 for PR). Per @taion's docs in #3178, this isn't actually a feature we need.
- [ ] Scroll position management. See [taion/scroll-behavior](https://github.com/taion/scroll-behavior) for a history enhancer approach. However, I agree with @taion when [he says](https://github.com/taion/rrtr/issues/13) that it's something that needs to be integrated into the router core. I also agree with @ryanflorence when [he says](https://gist.github.com/ryanflorence/08a056374e24a7cda3c459e3d7d63e6e) that it's very difficult to generalize scroll management, which is why we removed it in 1.0.

As the discussion progresses, I'd like to expand this list, identify changes that we can make together and them into changesets with a release type (e.g. `patch`, `minor`, or `major`) so we can minimize upgrade pain.

**Please keep comments short and to the point. Off-topic and excessively lengthy comments will be moderated.**

**Comment by timdorr** [comment]
Re: #3280, that was because of issues like #3279.

**Comment by taion** [comment]
#3158 isn't supporting trailing slashes, it's dropping support for extra slashes. On 2.1.1, `/foo/bar` matches `/foo////////bar//////`. Among other problems, paths don't even have a "nearly canonical" form net of the trailing slash.

**Comment by taion** [comment]
- #3158 was reverted because it caused a regression when using a basename – `useBasename` strips the leading slash from `location.pathname` when the basename has a trailing slash. That's why @timdorr cherry-picked https://github.com/taion/rrtr/pull/8, which also adds a test case.
- The change to `<Link>` would be breaking, and probably needs to come after removing support for nested routes with absolute paths. It's the correct resolution to https://github.com/reactjs/react-router/issues/3277, IMO.
- Regex stuff aside, being able to fail to match a route in-place because of "data not found" is IMO a requirement. I think https://github.com/reactjs/react-router/pull/3098 has a nice API, but again it's blocked on actually fixing #3172 (not just the deprecation warning), so probably needs a major release. Something like https://gist.github.com/ryanflorence/a311ca980c0d8a5d33eab50f29621f12 is extremely unsatisfying.

**Comment by timdorr** [comment]
For the conditional stuff, what if the onEnter/onChange hooks had a 4th arg that was an error callback.

**Comment by taion** [comment]
You can already call back with an error. The problem is that those errors can't be caught in a semantic way. Also, raising an error is not as rich as just falling through in routing. I really do think the API in #3098 is quite nice; it does exactly what's needed here.

**Comment by timdorr** [comment]
I like that one too. Just brainstorming some other options in case there is something more palatable to those that don't like the extra prop.

**Comment by taion** [comment]
I updated the OP to a checklist, and checked off the two things that we already resolved.

**Comment by timdorr** [comment]
I'd like to merge @ryanflorence's [applyMiddleware](https://github.com/ryanflorence/react-router-apply-middleware) into core. No reason not to have it.

**Comment by ryanflorence** [comment]
I'm making a tweak that @taion and I talked about last night before I make a pull request, it further simplifies creating middleware components.

**Comment by taion** [comment]
We have two scroll management middlewares now: https://github.com/ryanflorence/react-router-restore-scroll, https://github.com/taion/react-router-scroll. Naturally, I like mine more, but we should probably have one with the union of the feature set :p

**Comment by taion** [comment]
I'm going to fold this into an updated meta issue for the upcoming 3.x release, intended as a minor update to the 2.x API.

**Comment by taion** [comment]
Tracking concrete goals and maybe-goals for v3.0.0 on https://github.com/reactjs/react-router/issues/3611.
