### ISSUE TITLE
[META] 3.0.0-alpha.0

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3445]
I'm sorry, I would have just gotten to these but I've been really slammed. This is just a list of what I'd like to resolve before cutting 3.0.0-pre.0.

- [x] Put `routes` on `context.router` (and inject in `withRouter`)
- [ ] Move out `ContextUtils` into a separate library (I've already name-squatted `react-context-subscriber`)
- [x] Figure out if we can avoid calling `createRouterObject` on both https://github.com/reactjs/react-router/blob/17a362556f49f780a585f7ef6fcbe79b4311307e/modules/Router.js#L86 and https://github.com/reactjs/react-router/blob/17a362556f49f780a585f7ef6fcbe79b4311307e/modules/Router.js#L94

**Comment by timdorr** [comment]
For the `createRouterObject` issue, why did we go with wrapping up `location` and `params` into `router` before putting it on context? As implemented, it seems pretty messy to me, particularly around the identity maintenance. 

Here's the question I'm asking in my head: Do we need the `location` and `params` wrapped up into `router` somewhere where context *isn't* involved? It seems like either those values (or some form of `state`) is available whenever it gets passed around. So, we're moving them up higher in the composition, but with bad side-effects that make the code at that level less clear (because it's tied to effects in other parts of the code).

**Comment by taion** [comment]
We were maintaining the identity of the `router` object anyway, and it avoids doing something a lot messier to get `context.router` to update in `<Link>`.

We don't need those to be on `router` where context isn't involved, but it seems like less to keep track of if we don't have some weird rule that "`props.router` in a router context doesn't have `params` and `location`, but only `context.router` does".

**Comment by timdorr** [comment]
OK, not a huge deal then. I just see a new dep and start to pump the brakes at little bit.

Anyways, it should be fixed by #3446.

For putting `route` on context, we need a `RouteContext` don't we? (not the mixin)

**Comment by taion** [comment]
`routes`, not `route`

I just want `context.router` and `withRouter` to be as symmetric as possible to route components, which all receive `routes`, `location`, and `params`.

**Comment by timdorr** [comment]
Threw that into #3446 for you.

**Comment by taion** [comment]
@timdorr Thanks. I'll take care of that last bit either tomorrow or Thursday. Sorry this has been taking so long.

**Comment by ayrton** [comment]
@taion if there's anything I can do to help, happy to lend a hand 😄

**Comment by taion** [comment]
I'll have some time to look at this today or tomorrow. Sorry for the delay.

**Comment by ayrton** [comment]
Not trying to rush you, just checking if any help is needed

**Comment by gaearon** [comment]
Can we release a prerelease before pulling that code out? It’s an implementation detail so we can do it later at an RC stage. I’m going to need that version for a workshop I’ll be running soon, so it would be great if we could get it out.

**Comment by taion** [comment]
I'll cut the prerelease today either way. Sorry it's taken so long.

**Comment by gaearon** [comment]
No problem, and thank you for all your help!

**Comment by taion** [comment]
Okay, given the caveats with ContextUtils, let's leave it in here for now to make iterating on it easier. I still want to pull it out before we cut 3.0.0-final, but it's likely just going to be more effort for everyone involved if we pull it out at this point.

This seems on the surface inconsistent with how we're handling things like scroll behavior and relative links, but the difference is that this isn't actually a modular add-on but instead a core dependency.

**Comment by taion** [comment]
BTW, going forward, let's merge instead of cherry-pick onto next. I know it makes the commit history sort of ugly, but actually `git bisect` deals with this sort of thing now, and it just makes it easier to keep the branches in sync (since you can just do `git merge master` from `next`).

**Comment by taion** [comment]
Ahh, it has to be an alpha because of the alphabet. Oops.

**Comment by taion** [comment]
v3.0.0-alpha.1 is out. Sorry again it was blocked for so long on me.

**Comment by taion** [comment]
I think I found all the PRs for the changelog, but let me know if I missed anything: https://github.com/reactjs/react-router/commit/5832f2a254c489a0f81f9c6a54188c4247a0570c
